[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python check_dependencies.py || echo 'Dependency check failed but continuing build'"

[deploy]
startCommand = "python -m src.health & sleep 5 && python -m src.main & python -m src.communicator_bot.main & wait"
healthcheckPath = "/health"
healthcheckTimeout = 15
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5

[nixpacks]
pkgs = ["python310", "gcc", "build-essential", "curl", "python310Packages.pip"]
