[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m src.main & python -m src.communicator_bot.main & python -m src.health & wait"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyMaxRetries = 5

[nixpacks]
pkgs = ["python310", "gcc", "build-essential", "curl"]
