[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python check_dependencies.py || echo 'Dependency check failed but continuing build'"

[deploy]
startCommand = "python -m src.main"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10

[nixpacks]
pkgs = ["python310", "gcc", "build-essential", "curl", "python310Packages.pip"]
